title: Process Yellow
email: matt@processyellow.ca

url: "http://processyellow.ca"

markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - node_modules
  - gulpfile.js
permalink: pretty
